<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_edit.blade.php" was generated by ProBot AI.
* Date: 10/28/2025 2:36:59 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Product')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('products.index')}}">Manage</a>
<form action="{{route('products.update',$product)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="id" class="col-sm-2 col-form-label">Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="id" value="{{$product->id}}" id="id" placeholder="Id">
	</div>
</div>
<div class="row mb-3">
	<label for="category_id" class="col-sm-2 col-form-label">Category Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="category_id" value="{{$product->category_id}}" id="category_id" placeholder="Category Id">
	</div>
</div>
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$product->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$product->price}}" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="stock" class="col-sm-2 col-form-label">Stock</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="stock" value="{{$product->stock}}" id="stock" placeholder="Stock">
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="description" value="{{$product->description}}" id="description" placeholder="Description">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
