<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_index.blade.php" was generated by ProBot AI.
* Date: 10/28/2025 2:36:59 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Product')
@section('style')


@endsection
@section('page')
<a href="{{route('products.create')}}">New Product</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Category Id</th>
			<th>Name</th>
			<th>Price</th>
			<th>Stock</th>
			<th>Description</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($products as $product)
		<tr>
			<td>{{$product->id}}</td>
			<td>{{$product->category_id}}</td>
			<td>{{$product->name}}</td>
			<td>{{$product->price}}</td>
			<td>{{$product->stock}}</td>
			<td>{{$product->description}}</td>
			<td>{{$product->created_at}}</td>
			<td>{{$product->updated_at}}</td>

			<td>
			<form action = "{{route('products.destroy',$product->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('products.show',$product->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('products.edit',$product->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
