<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/supplier/_show.blade.php" was generated by ProBot AI.
* Date: 10/28/2025 2:37:28 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Supplier')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('suppliers.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$supplier->id}}</td></tr>
		<tr><th>Name</th><td>{{$supplier->name}}</td></tr>
		<tr><th>Phone</th><td>{{$supplier->phone}}</td></tr>
		<tr><th>Company</th><td>{{$supplier->company}}</td></tr>
		<tr><th>Email</th><td>{{$supplier->email}}</td></tr>
		<tr><th>Address</th><td>{{$supplier->address}}</td></tr>
		<tr><th>Created At</th><td>{{$supplier->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$supplier->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
