<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PurchaseReturnDetail.php" was generated by ProBot AI.
* Date: 3/5/2025 11:31:32 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PurchaseReturnDetail extends Model{
    public function products() {
        
        return $this->belongsTo(Product::class);
    }


}
?>
