<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Supplier.php" was generated by ProBot AI.
* Date: 10/28/2025 2:37:28 PM
* Contact: towhid1@outlook.com
*/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    protected $fillable = [
        'name',
        'phone',
        'company',
        'email',
        'address'
    ];
}
